#!/usr/bin/env bash
# =============================================================================
#  ███████╗██╗     ██╗███╗   ██╗████████╗    ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗
#  ██╔════╝██║     ██║████╗  ██║╚══██╔══╝    ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝
#  █████╗  ██║     ██║██╔██╗ ██║   ██║       ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝
#  ██╔══╝  ██║     ██║██║╚██╗██║   ██║       ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗
#  ██║     ███████╗██║██║ ╚████║   ██║       ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗
#  ╚═╝     ╚══════╝╚═╝╚═╝  ╚═══╝   ╚═╝       ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝
# =============================================================================
#  Flint Linux — LFS Automated Build Script
#  Target:  Lenovo ThinkPad T460 | Intel i7-6600U (Skylake) | 12 GB RAM
#  Init:    dinit
#  WM:      Hyprland + Waybar + Foot
#  Pkgmgr: Pacman (bootstrapped)
#  Author:  Generated by Claude (Anthropic) — Senior Systems Engineer Mode
# =============================================================================
#
#  USAGE:
#    sudo bash flint-lfs.sh [PHASE]
#
#  PHASES (idempotent — safe to re-run from any phase):
#    all     — Run all phases (default)
#    1       — Toolchain (Binutils, GCC, Glibc cross-tools)
#    2       — Chroot + final system build
#    3       — Post-install (bootloader, Hyprland, Fastfetch, dinit)
#    check   — Pre-flight dependency check only
#
#  RESUME:  If the script fails, re-run with the same PHASE argument.
#           Completed steps are tracked in $LFS/flint_state/
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# ─────────────────────────────────────────────────────────────────────────────
# GLOBAL CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
export LFS=/mnt/lfs
export LFS_TGT="x86_64-lfs-linux-gnu"
export FLINT_VERSION="1.0.0"
export FLINT_CODENAME="Obsidian"

# CPU / Compiler Optimizations — Skylake-specific
export CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
export MAKEFLAGS="-j$(nproc)"

# Parallel jobs — use all cores
NPROC=$(nproc)
JOBS="${NPROC}"

# Source versions (pinned for reproducibility)
BINUTILS_VERSION="2.42"
GCC_VERSION="14.1.0"
GLIBC_VERSION="2.39"
MPFR_VERSION="4.2.1"
GMP_VERSION="6.3.0"
MPC_VERSION="1.3.1"
LINUX_VERSION="6.9.3"
ZLIB_VERSION="1.3.1"
BZIP2_VERSION="1.0.8"
XZ_VERSION="5.4.6"
ZSTD_VERSION="1.5.6"
FILE_VERSION="5.45"
READLINE_VERSION="8.2"
M4_VERSION="1.4.19"
BC_VERSION="6.7.6"
FLEX_VERSION="2.6.4"
TCL_VERSION="8.6.14"
EXPECT_VERSION="5.45.4"
DEJAGNU_VERSION="1.6.3"
PKGCONF_VERSION="2.2.0"
NCURSES_VERSION="6.5"
BASH_VERSION="5.2.21"
COREUTILS_VERSION="9.5"
DIFFUTILS_VERSION="3.10"
GAWK_VERSION="5.3.0"
FINDUTILS_VERSION="4.9.0"
GREP_VERSION="3.11"
GZIP_VERSION="1.13"
MAKE_VERSION="4.4.1"
PATCH_VERSION="2.7.6"
SED_VERSION="4.9"
TAR_VERSION="1.35"
TEXINFO_VERSION="7.1"
UTIL_LINUX_VERSION="2.40"
PERL_VERSION="5.38.2"
PYTHON_VERSION="3.12.3"
OPENSSL_VERSION="3.3.0"
SHADOW_VERSION="4.15.1"
PSMISC_VERSION="23.7"
PROCPS_VERSION="4.0.4"
E2FSPROGS_VERSION="1.47.1"
KMOD_VERSION="32"
LIBCAP_VERSION="2.70"
IPROUTE2_VERSION="6.9.0"
LESS_VERSION="661"
VIM_VERSION="9.1.0"
DINIT_VERSION="0.19.1"
PACMAN_VERSION="6.1.0"
HYPRLAND_VERSION="0.41.2"
WAYBAR_VERSION="0.10.3"
FOOT_VERSION="1.17.2"
FASTFETCH_VERSION="2.11.4"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# State tracking directory (idempotency)
STATE_DIR="${LFS}/flint_state"
SOURCES_DIR="${LFS}/sources"
LOG_DIR="${LFS}/flint_logs"

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING & STATE HELPERS
# ─────────────────────────────────────────────────────────────────────────────
log()     { echo -e "${BOLD}${BLUE}[FLINT]${NC} $*"; }
info()    { echo -e "${CYAN}  →${NC} $*"; }
success() { echo -e "${GREEN}  ✓${NC} $*"; }
warn()    { echo -e "${YELLOW}  ⚠${NC} $*"; }
error()   { echo -e "${RED}  ✗ ERROR:${NC} $*" >&2; }
die()     { error "$*"; exit 1; }

banner() {
    echo -e "${BOLD}${BLUE}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  $*"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${NC}"
}

# Mark a step as done
step_done() {
    local step="$1"
    mkdir -p "${STATE_DIR}"
    touch "${STATE_DIR}/${step}.done"
    success "Step '${step}' complete."
}

# Check if a step is already done
step_is_done() {
    local step="$1"
    [[ -f "${STATE_DIR}/${step}.done" ]]
}

# Idempotent step runner
run_step() {
    local step="$1"
    local desc="$2"
    shift 2
    if step_is_done "${step}"; then
        info "Skipping '${desc}' (already done)"
        return 0
    fi
    log "Running: ${desc}"
    mkdir -p "${LOG_DIR}"
    if "$@" 2>&1 | tee "${LOG_DIR}/${step}.log"; then
        step_done "${step}"
    else
        die "Step '${step}' failed. See ${LOG_DIR}/${step}.log"
    fi
}

# Download with resume support
fetch_source() {
    local url="$1"
    local filename="${2:-$(basename "$url")}"
    local dest="${SOURCES_DIR}/${filename}"
    if [[ -f "${dest}" ]]; then
        info "Already downloaded: ${filename}"
        return 0
    fi
    info "Downloading: ${filename}"
    wget -c --progress=bar:force -O "${dest}" "${url}" \
        || curl -L --progress-bar -C - -o "${dest}" "${url}"
}

extract_and_cd() {
    local tarball="$1"
    local dest_name="${2:-}"
    cd /tmp/flint_build
    rm -rf ./*  2>/dev/null || true
    tar xf "${SOURCES_DIR}/${tarball}"
    if [[ -n "${dest_name}" ]]; then
        cd "${dest_name}"
    else
        cd "$(tar tf "${SOURCES_DIR}/${tarball}" | head -1 | cut -d/ -f1)"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# PRE-FLIGHT CHECKS
# ─────────────────────────────────────────────────────────────────────────────
preflight_check() {
    banner "Flint Linux — Pre-flight Check"

    [[ "${EUID}" -eq 0 ]] || die "This script must be run as root."

    local required_tools=(
        bash awk bison bzip2 chroot diff find gawk gcc g++ gzip
        m4 make patch perl python3 sed tar texinfo xz wget
    )
    local missing=()
    for tool in "${required_tools[@]}"; do
        if ! command -v "${tool}" &>/dev/null; then
            missing+=("${tool}")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        die "Missing host tools: ${missing[*]}\nInstall them and re-run."
    fi

    # Version checks
    local bash_ver
    bash_ver=$(bash --version | head -1 | grep -oP '\d+\.\d+' | head -1)
    info "Bash: ${bash_ver}"

    local gcc_ver
    gcc_ver=$(gcc -dumpversion)
    info "GCC: ${gcc_ver}"

    local kernel_ver
    kernel_ver=$(uname -r)
    info "Host kernel: ${kernel_ver}"

    # Ensure /mnt/lfs is on a real filesystem (not tmpfs)
    if mountpoint -q "${LFS}" 2>/dev/null; then
        local fs_type
        fs_type=$(stat -f -c%T "${LFS}")
        info "LFS mount: ${LFS} (${fs_type})"
    else
        warn "${LFS} is not a separate mountpoint. Ensure your LFS partition is mounted."
    fi

    # Disk space check — need at least 50GB free
    local free_gb
    free_gb=$(df -BG "${LFS}" | awk 'NR==2{print $4}' | tr -d G)
    if [[ "${free_gb}" -lt 50 ]]; then
        warn "Only ${free_gb}GB free on ${LFS}. Recommended: 50GB+"
    else
        success "Disk space OK: ${free_gb}GB free"
    fi

    # RAM check
    local ram_gb
    ram_gb=$(free -g | awk '/^Mem:/{print $2}')
    info "RAM: ${ram_gb}GB"

    success "Pre-flight checks passed!"
}

# ─────────────────────────────────────────────────────────────────────────────
# ENVIRONMENT SETUP
# ─────────────────────────────────────────────────────────────────────────────
setup_environment() {
    banner "Phase 0 — Environment Setup"

    run_step "env_dirs" "Create LFS directory structure" _create_dirs
    run_step "env_sources" "Download all source tarballs" _download_sources
    run_step "env_lfs_user" "Create lfs build user" _create_lfs_user
    run_step "env_symlinks" "Create /tools symlink" _create_symlinks
}

_create_dirs() {
    mkdir -p "${LFS}"/{sources,tools,flint_state,flint_logs}
    mkdir -p /tmp/flint_build
    chmod a+wt "${SOURCES_DIR}"
    # LFS book directory structure
    mkdir -p "${LFS}"/{boot,etc/{opt,profile.d},home,lib/firmware,lib64}
    mkdir -p "${LFS}"/{media/{floppy,cdrom},mnt,opt,proc,run}
    mkdir -p "${LFS}"/{srv,sys,tmp,usr,var}
    mkdir -p "${LFS}"/usr/{bin,include,lib,lib64,libexec,local,sbin,share,src}
    mkdir -p "${LFS}"/usr/local/{bin,include,lib,sbin,share}
    mkdir -p "${LFS}"/usr/share/{color,dict,doc,info,locale,man}
    mkdir -p "${LFS}"/usr/share/{misc,terminfo,zoneinfo}
    mkdir -p "${LFS}"/usr/share/man/man{1..8}
    mkdir -p "${LFS}"/var/{cache,lib,local,log,mail,opt,spool,tmp}
    install -dv -m 0750 "${LFS}"/root
    install -dv -m 1777 "${LFS}"/tmp "${LFS}"/var/tmp
    # Create essential symlinks
    ln -sfn usr/bin "${LFS}"/bin
    ln -sfn usr/bin "${LFS}"/sbin
    ln -sfn usr/lib "${LFS}"/lib
    ln -sfn usr/lib64 "${LFS}"/lib64
    ln -sfn usr/sbin "${LFS}"/usr/sbin  2>/dev/null || true
    # Compatibility
    ln -sfn /proc/self/mounts "${LFS}"/etc/mtab 2>/dev/null || true
}

_create_lfs_user() {
    if ! id lfs &>/dev/null; then
        groupadd lfs 2>/dev/null || true
        useradd -s /bin/bash -g lfs -m -k /dev/null lfs
    fi
    chown -R lfs:lfs "${LFS}"/tools "${SOURCES_DIR}" 2>/dev/null || true
    chown lfs:lfs "${LFS}" 2>/dev/null || true

    # lfs user bashrc
    cat > /home/lfs/.bash_profile <<'EOF'
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF
    cat > /home/lfs/.bashrc <<EOF
set +h
umask 022
LFS=${LFS}
LC_ALL=POSIX
LFS_TGT=${LFS_TGT}
PATH=/usr/bin:/bin:/usr/sbin:/sbin:\${LFS}/tools/bin
CONFIG_SITE=\${LFS}/usr/share/config.site
CFLAGS="${CFLAGS}"
CXXFLAGS="${CXXFLAGS}"
LDFLAGS="${LDFLAGS}"
MAKEFLAGS="${MAKEFLAGS}"
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE CFLAGS CXXFLAGS LDFLAGS MAKEFLAGS
EOF
    chown lfs:lfs /home/lfs/.bash_profile /home/lfs/.bashrc
}

_create_symlinks() {
    # /tools lives inside $LFS for chroot compatibility
    [[ -d "${LFS}/tools" ]] || mkdir -p "${LFS}/tools"
    ln -sfn "${LFS}/tools" /tools 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────────────────────
# SOURCE DOWNLOADS
# ─────────────────────────────────────────────────────────────────────────────
_download_sources() {
    mkdir -p "${SOURCES_DIR}"

    local GNU="https://ftp.gnu.org/gnu"
    local KERNEL="https://cdn.kernel.org/pub/linux/kernel/v6.x"

    declare -A SOURCES=(
        ["binutils-${BINUTILS_VERSION}.tar.xz"]="${GNU}/binutils/binutils-${BINUTILS_VERSION}.tar.xz"
        ["gcc-${GCC_VERSION}.tar.xz"]="${GNU}/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.xz"
        ["glibc-${GLIBC_VERSION}.tar.xz"]="${GNU}/libc/glibc-${GLIBC_VERSION}.tar.xz"
        ["mpfr-${MPFR_VERSION}.tar.xz"]="${GNU}/mpfr/mpfr-${MPFR_VERSION}.tar.xz"
        ["gmp-${GMP_VERSION}.tar.xz"]="${GNU}/gmp/gmp-${GMP_VERSION}.tar.xz"
        ["mpc-${MPC_VERSION}.tar.gz"]="${GNU}/mpc/mpc-${MPC_VERSION}.tar.gz"
        ["linux-${LINUX_VERSION}.tar.xz"]="${KERNEL}/linux-${LINUX_VERSION}.tar.xz"
        ["zlib-${ZLIB_VERSION}.tar.gz"]="https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz"
        ["bzip2-${BZIP2_VERSION}.tar.gz"]="${GNU}/bzip2/bzip2-${BZIP2_VERSION}.tar.gz"
        ["xz-${XZ_VERSION}.tar.xz"]="https://github.com/tukaani-project/xz/releases/download/v${XZ_VERSION}/xz-${XZ_VERSION}.tar.xz"
        ["zstd-${ZSTD_VERSION}.tar.gz"]="https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz"
        ["file-${FILE_VERSION}.tar.gz"]="https://astron.com/pub/file/file-${FILE_VERSION}.tar.gz"
        ["readline-${READLINE_VERSION}.tar.gz"]="${GNU}/readline/readline-${READLINE_VERSION}.tar.gz"
        ["m4-${M4_VERSION}.tar.xz"]="${GNU}/m4/m4-${M4_VERSION}.tar.xz"
        ["bc-${BC_VERSION}.tar.xz"]="https://github.com/gavinhoward/bc/releases/download/${BC_VERSION}/bc-${BC_VERSION}.tar.xz"
        ["flex-${FLEX_VERSION}.tar.gz"]="https://github.com/westes/flex/releases/download/v${FLEX_VERSION}/flex-${FLEX_VERSION}.tar.gz"
        ["tcl${TCL_VERSION}-src.tar.gz"]="https://sourceforge.net/projects/tcl/files/Tcl/${TCL_VERSION}/tcl${TCL_VERSION}-src.tar.gz"
        ["expect${EXPECT_VERSION}.tar.gz"]="https://sourceforge.net/projects/expect/files/Expect/${EXPECT_VERSION}/expect${EXPECT_VERSION}.tar.gz"
        ["dejagnu-${DEJAGNU_VERSION}.tar.gz"]="${GNU}/dejagnu/dejagnu-${DEJAGNU_VERSION}.tar.gz"
        ["pkgconf-${PKGCONF_VERSION}.tar.xz"]="https://distfiles.ariadne.space/pkgconf/pkgconf-${PKGCONF_VERSION}.tar.xz"
        ["ncurses-${NCURSES_VERSION}.tar.gz"]="${GNU}/ncurses/ncurses-${NCURSES_VERSION}.tar.gz"
        ["bash-${BASH_VERSION}.tar.gz"]="${GNU}/bash/bash-${BASH_VERSION}.tar.gz"
        ["coreutils-${COREUTILS_VERSION}.tar.xz"]="${GNU}/coreutils/coreutils-${COREUTILS_VERSION}.tar.xz"
        ["diffutils-${DIFFUTILS_VERSION}.tar.xz"]="${GNU}/diffutils/diffutils-${DIFFUTILS_VERSION}.tar.xz"
        ["gawk-${GAWK_VERSION}.tar.xz"]="${GNU}/gawk/gawk-${GAWK_VERSION}.tar.xz"
        ["findutils-${FINDUTILS_VERSION}.tar.xz"]="${GNU}/findutils/findutils-${FINDUTILS_VERSION}.tar.xz"
        ["grep-${GREP_VERSION}.tar.xz"]="${GNU}/grep/grep-${GREP_VERSION}.tar.xz"
        ["gzip-${GZIP_VERSION}.tar.xz"]="${GNU}/gzip/gzip-${GZIP_VERSION}.tar.xz"
        ["make-${MAKE_VERSION}.tar.gz"]="${GNU}/make/make-${MAKE_VERSION}.tar.gz"
        ["patch-${PATCH_VERSION}.tar.xz"]="${GNU}/patch/patch-${PATCH_VERSION}.tar.xz"
        ["sed-${SED_VERSION}.tar.xz"]="${GNU}/sed/sed-${SED_VERSION}.tar.xz"
        ["tar-${TAR_VERSION}.tar.xz"]="${GNU}/tar/tar-${TAR_VERSION}.tar.xz"
        ["texinfo-${TEXINFO_VERSION}.tar.xz"]="${GNU}/texinfo/texinfo-${TEXINFO_VERSION}.tar.xz"
        ["util-linux-${UTIL_LINUX_VERSION}.tar.xz"]="https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v${UTIL_LINUX_VERSION%.*}/util-linux-${UTIL_LINUX_VERSION}.tar.xz"
        ["perl-${PERL_VERSION}.tar.xz"]="https://www.cpan.org/src/5.0/perl-${PERL_VERSION}.tar.xz"
        ["Python-${PYTHON_VERSION}.tar.xz"]="https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz"
        ["openssl-${OPENSSL_VERSION}.tar.gz"]="https://openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz"
        ["shadow-${SHADOW_VERSION}.tar.xz"]="https://github.com/shadow-maint/shadow/releases/download/${SHADOW_VERSION}/shadow-${SHADOW_VERSION}.tar.xz"
        ["psmisc-${PSMISC_VERSION}.tar.xz"]="https://gitlab.com/psmisc/psmisc/-/archive/v${PSMISC_VERSION}/psmisc-v${PSMISC_VERSION}.tar.gz"
        ["procps-ng-${PROCPS_VERSION}.tar.xz"]="https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-${PROCPS_VERSION}.tar.xz"
        ["e2fsprogs-${E2FSPROGS_VERSION}.tar.gz"]="https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v${E2FSPROGS_VERSION}/e2fsprogs-${E2FSPROGS_VERSION}.tar.gz"
        ["kmod-${KMOD_VERSION}.tar.xz"]="https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-${KMOD_VERSION}.tar.xz"
        ["libcap-${LIBCAP_VERSION}.tar.xz"]="https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${LIBCAP_VERSION}.tar.xz"
        ["iproute2-${IPROUTE2_VERSION}.tar.xz"]="https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-${IPROUTE2_VERSION}.tar.xz"
        ["less-${LESS_VERSION}.tar.gz"]="https://www.greenwoodsoftware.com/less/less-${LESS_VERSION}.tar.gz"
    )

    for filename in "${!SOURCES[@]}"; do
        fetch_source "${SOURCES[$filename]}" "${filename}"
    done

    # dinit
    fetch_source "https://github.com/davmac314/dinit/archive/refs/tags/v${DINIT_VERSION}.tar.gz" \
        "dinit-${DINIT_VERSION}.tar.gz"

    # pacman
    fetch_source "https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz" \
        "pacman-${PACMAN_VERSION}.tar.xz"

    success "All sources downloaded."
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 1 — CROSS-TOOLCHAIN
# ─────────────────────────────────────────────────────────────────────────────
phase1_toolchain() {
    banner "Phase 1 — Cross-Toolchain Build (runs as lfs user)"

    # These build steps run as lfs user for safety
    local PHASE1_SCRIPT="/tmp/flint_phase1_inner.sh"

    cat > "${PHASE1_SCRIPT}" <<'INNER'
#!/usr/bin/env bash
set -euo pipefail

# Re-import environment
source /home/lfs/.bashrc

BUILD_DIR="/tmp/flint_build"
SRC="${LFS}/sources"
TOOLS="${LFS}/tools"
STATE="${LFS}/flint_state"
LOGS="${LFS}/flint_logs"

step_done()    { mkdir -p "${STATE}"; touch "${STATE}/$1.done"; echo "  ✓ $1 done"; }
step_is_done() { [[ -f "${STATE}/$1.done" ]]; }
run_step() {
    local step="$1" desc="$2"; shift 2
    step_is_done "${step}" && { echo "  → Skipping ${desc}"; return 0; }
    echo "[PHASE1] ${desc}"
    mkdir -p "${LOGS}"
    "$@" 2>&1 | tee "${LOGS}/${step}.log"
    step_done "${step}"
}

mk() { rm -rf "${BUILD_DIR}"/*; mkdir -p "${BUILD_DIR}"; cd "${BUILD_DIR}"; }
extr() {
    cd /tmp
    rm -rf flint_build/* 2>/dev/null || true
    mkdir -p flint_build
    cd flint_build
    tar xf "${SRC}/$1"
    cd "$(tar tf "${SRC}/$1" | head -1 | cut -d/ -f1)"
}

# ── 1.1 Binutils Pass 1 ───────────────────────────────────────────────────
build_binutils_pass1() {
    extr "binutils-2.42.tar.xz"
    mkdir -v build && cd build
    ../configure                     \
        --prefix="${LFS}"/tools      \
        --with-sysroot="${LFS}"      \
        --target="${LFS_TGT}"        \
        --disable-nls                \
        --enable-gprofng=no          \
        --disable-werror             \
        --enable-new-dtags           \
        --enable-default-hash-style=gnu
    make -j"${NPROC:-$(nproc)}"
    make install
}
NPROC=$(nproc)
run_step "p1_binutils1" "Binutils Pass 1" build_binutils_pass1

# ── 1.2 GCC Pass 1 ────────────────────────────────────────────────────────
build_gcc_pass1() {
    extr "gcc-14.1.0.tar.xz"
    # Unpack prerequisites into gcc source tree
    tar xf "${SRC}/mpfr-4.2.1.tar.xz"; mv mpfr-4.2.1 mpfr
    tar xf "${SRC}/gmp-6.3.0.tar.xz";  mv gmp-6.3.0  gmp
    tar xf "${SRC}/mpc-1.3.1.tar.gz";  mv mpc-1.3.1  mpc

    # Ensure 64-bit libs go to lib (not lib64) inside the sysroot
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64

    mkdir -v build && cd build
    ../configure                                   \
        --target="${LFS_TGT}"                      \
        --prefix="${LFS}"/tools                    \
        --with-glibc-version=2.39                  \
        --with-sysroot="${LFS}"                    \
        --with-newlib                              \
        --without-headers                          \
        --enable-default-pie                       \
        --enable-default-ssp                       \
        --disable-nls                              \
        --disable-shared                           \
        --disable-multilib                         \
        --disable-threads                          \
        --disable-libatomic                        \
        --disable-libgomp                          \
        --disable-libquadmath                      \
        --disable-libssp                           \
        --disable-libvtv                           \
        --disable-libstdcxx                        \
        --enable-languages=c,c++

    make -j"${NPROC}"
    make install

    # Build limits.h for glibc compatibility
    cd ..
    cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
        "$(dirname "$("${LFS_TGT}-gcc" -print-libgcc-file-name)")/include/limits.h"
}
run_step "p1_gcc1" "GCC Pass 1" build_gcc_pass1

# ── 1.3 Linux API Headers ─────────────────────────────────────────────────
build_linux_headers() {
    extr "linux-6.9.3.tar.xz"
    make mrproper
    make headers
    find usr/include -type f ! -name '*.h' -delete
    cp -rv usr/include "${LFS}"/usr/
}
run_step "p1_linux_headers" "Linux API Headers" build_linux_headers

# ── 1.4 Glibc ─────────────────────────────────────────────────────────────
build_glibc() {
    extr "glibc-2.39.tar.xz"
    # Fix FHS compliance
    ln -sfn ../lib/ld-linux-x86-64.so.2 "${LFS}"/lib64/ld-linux-x86-64.so.2      2>/dev/null || true
    ln -sfn ../lib/ld-linux-x86-64.so.2 "${LFS}"/lib64/ld-lsb-x86-64.so.3       2>/dev/null || true

    mkdir -v build && cd build
    echo "rootsbindir=/usr/sbin" > configparms
    ../configure                              \
        --prefix=/usr                         \
        --host="${LFS_TGT}"                   \
        --build="$(../scripts/config.guess)"  \
        --enable-kernel=4.19                  \
        --with-headers="${LFS}"/usr/include   \
        --disable-nscd                        \
        libc_cv_slibdir=/usr/lib

    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    sed '/RTLDLIST=/s@/usr@@g' -i "${LFS}"/usr/bin/ldd
}
run_step "p1_glibc" "Glibc (C Library)" build_glibc

# ── 1.5 Libstdc++ (from GCC) ──────────────────────────────────────────────
build_libstdcxx() {
    extr "gcc-14.1.0.tar.xz"
    mkdir -v build && cd build
    ../libstdc++-v3/configure           \
        --host="${LFS_TGT}"             \
        --build="$(../config.guess)"    \
        --prefix=/usr                   \
        --disable-multilib              \
        --disable-nls                   \
        --disable-libstdcxx-pch         \
        --with-gxx-include-dir=/tools/"${LFS_TGT}"/include/c++/14.1.0

    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    rm -v "${LFS}"/usr/lib/lib{stdc++{,exp},supc++}.la
}
run_step "p1_libstdcxx" "Libstdc++" build_libstdcxx

# ── 1.6 M4 ────────────────────────────────────────────────────────────────
build_m4() {
    extr "m4-1.4.19.tar.xz"
    ./configure --prefix=/usr           \
                --host="${LFS_TGT}"     \
                --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
}
run_step "p1_m4" "M4" build_m4

# ── 1.7 Ncurses ───────────────────────────────────────────────────────────
build_ncurses() {
    extr "ncurses-6.5.tar.gz"
    sed -i s/mawk// configure
    mkdir -v build
    pushd build
        ../configure
        make -C include
        make -C progs tic
    popd
    ./configure                         \
        --prefix=/usr                   \
        --host="${LFS_TGT}"             \
        --build="$(./config.guess)"     \
        --mandir=/usr/share/man         \
        --with-manpage-format=normal    \
        --with-shared                   \
        --without-normal                \
        --with-cxx-shared               \
        --without-debug                 \
        --without-ada                   \
        --disable-stripping             \
        --enable-widec

    make -j"${NPROC}"
    make DESTDIR="${LFS}" TIC_PATH="$(pwd)/build/progs/tic" install
    ln -sv libncursesw.so "${LFS}"/usr/lib/libncurses.so
    sed -e 's/^#if.*XOPEN.*$/#if 1/' \
        -i "${LFS}"/usr/include/curses.h
}
run_step "p1_ncurses" "Ncurses" build_ncurses

# ── 1.8 Bash ──────────────────────────────────────────────────────────────
build_bash() {
    extr "bash-5.2.21.tar.gz"
    ./configure                         \
        --prefix=/usr                   \
        --build="$(sh support/config.guess)" \
        --host="${LFS_TGT}"             \
        --without-bash-malloc
    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    ln -sv bash "${LFS}"/usr/bin/sh
}
run_step "p1_bash" "Bash" build_bash

# ── 1.9 Coreutils ─────────────────────────────────────────────────────────
build_coreutils() {
    extr "coreutils-9.5.tar.xz"
    ./configure                         \
        --prefix=/usr                   \
        --host="${LFS_TGT}"             \
        --build="$(./build-aux/config.guess)" \
        --enable-install-program=hostname \
        --enable-no-install-program=kill,uptime
    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    mv -v "${LFS}"/usr/bin/chroot   "${LFS}"/usr/sbin
    mkdir -pv "${LFS}"/usr/share/man/man8
    mv -v "${LFS}"/usr/share/man/man1/chroot.1 \
          "${LFS}"/usr/share/man/man8/chroot.8
    sed -i 's/"1"/"8"/' "${LFS}"/usr/share/man/man8/chroot.8
}
run_step "p1_coreutils" "Coreutils" build_coreutils

# ── 1.10 Diffutils ────────────────────────────────────────────────────────
build_diffutils() {
    extr "diffutils-3.10.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_diffutils" "Diffutils" build_diffutils

# ── 1.11 File ─────────────────────────────────────────────────────────────
build_file() {
    extr "file-5.45.tar.gz"
    mkdir -v build
    pushd build
        ../configure --disable-bzlib --disable-libseccomp --disable-xzlib --disable-zlib
        make -j"${NPROC}"
    popd
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./config.guess)"
    make FILE_COMPILE="$(pwd)/build/src/file" -j"${NPROC}"
    make DESTDIR="${LFS}" install
    rm "${LFS}"/usr/lib/libmagic.la
}
run_step "p1_file" "File" build_file

# ── 1.12 Findutils ────────────────────────────────────────────────────────
build_findutils() {
    extr "findutils-4.9.0.tar.xz"
    ./configure --prefix=/usr \
                --localstatedir=/var/lib/locate \
                --host="${LFS_TGT}" \
                --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_findutils" "Findutils" build_findutils

# ── 1.13 Gawk ─────────────────────────────────────────────────────────────
build_gawk() {
    extr "gawk-5.3.0.tar.xz"
    sed -i 's/extras//' Makefile.in
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_gawk" "Gawk" build_gawk

# ── 1.14 Grep ─────────────────────────────────────────────────────────────
build_grep() {
    extr "grep-3.11.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_grep" "Grep" build_grep

# ── 1.15 Gzip ─────────────────────────────────────────────────────────────
build_gzip() {
    extr "gzip-1.13.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_gzip" "Gzip" build_gzip

# ── 1.16 Make ─────────────────────────────────────────────────────────────
build_make() {
    extr "make-4.4.1.tar.gz"
    ./configure --prefix=/usr --without-guile --host="${LFS_TGT}" \
                --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_make" "Make" build_make

# ── 1.17 Patch ────────────────────────────────────────────────────────────
build_patch() {
    extr "patch-2.7.6.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_patch" "Patch" build_patch

# ── 1.18 Sed ──────────────────────────────────────────────────────────────
build_sed() {
    extr "sed-4.9.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_sed" "Sed" build_sed

# ── 1.19 Tar ──────────────────────────────────────────────────────────────
build_tar() {
    extr "tar-1.35.tar.xz"
    ./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./build-aux/config.guess)"
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
}
run_step "p1_tar" "Tar" build_tar

# ── 1.20 Xz ───────────────────────────────────────────────────────────────
build_xz() {
    extr "xz-5.4.6.tar.xz"
    ./configure --prefix=/usr          \
                --host="${LFS_TGT}"    \
                --build="$(./build-aux/config.guess)" \
                --disable-static       \
                --docdir=/usr/share/doc/xz-5.4.6
    make -j"${NPROC}"; make DESTDIR="${LFS}" install
    rm "${LFS}"/usr/lib/liblzma.la
}
run_step "p1_xz" "Xz" build_xz

# ── 1.21 Binutils Pass 2 ──────────────────────────────────────────────────
build_binutils_pass2() {
    extr "binutils-2.42.tar.xz"
    sed '6009s/$add_dir//' -i ltmain.sh
    mkdir -v build && cd build
    ../configure                       \
        --prefix=/usr                  \
        --build="$(../config.guess)"   \
        --host="${LFS_TGT}"            \
        --disable-nls                  \
        --enable-shared                \
        --enable-gprofng=no            \
        --disable-werror               \
        --enable-64-bit-bfd            \
        --enable-new-dtags             \
        --enable-default-hash-style=gnu
    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    rm -v "${LFS}"/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}
}
run_step "p1_binutils2" "Binutils Pass 2" build_binutils_pass2

# ── 1.22 GCC Pass 2 ───────────────────────────────────────────────────────
build_gcc_pass2() {
    extr "gcc-14.1.0.tar.xz"
    tar xf "${SRC}/mpfr-4.2.1.tar.xz"; mv mpfr-4.2.1 mpfr
    tar xf "${SRC}/gmp-6.3.0.tar.xz";  mv gmp-6.3.0  gmp
    tar xf "${SRC}/mpc-1.3.1.tar.gz";  mv mpc-1.3.1  mpc

    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
    sed '/thread_header =/s/@.*@/gthr-posix.h/' \
        -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

    mkdir -v build && cd build
    ../configure                               \
        --build="$(../config.guess)"           \
        --host="${LFS_TGT}"                    \
        --target=x86_64-pc-linux-gnu           \
        LDFLAGS_FOR_TARGET=-L"${PWD}/x86_64-pc-linux-gnu/libgcc" \
        --prefix=/usr                          \
        --with-build-sysroot="${LFS}"          \
        --enable-default-pie                   \
        --enable-default-ssp                   \
        --disable-nls                          \
        --disable-multilib                     \
        --disable-libatomic                    \
        --disable-libgomp                      \
        --disable-libquadmath                  \
        --disable-libsanitizer                 \
        --disable-libssp                       \
        --disable-libvtv                       \
        --enable-languages=c,c++

    make -j"${NPROC}"
    make DESTDIR="${LFS}" install
    ln -sv gcc "${LFS}"/usr/bin/cc
}
run_step "p1_gcc2" "GCC Pass 2" build_gcc_pass2

echo ""
echo "============================================"
echo "  Phase 1 Complete — Toolchain built!"
echo "============================================"
INNER

    chmod +x "${PHASE1_SCRIPT}"
    chown lfs:lfs "${PHASE1_SCRIPT}"

    # Run phase 1 as lfs user
    su - lfs -c "bash ${PHASE1_SCRIPT}"
}

# ─────────────────────────────────────────────────────────────────────────────
# CHROOT SETUP
# ─────────────────────────────────────────────────────────────────────────────
setup_chroot_mounts() {
    banner "Preparing Chroot Environment"

    run_step "chroot_mounts" "Mount virtual filesystems" _mount_vfs
    run_step "chroot_dirs"   "Create essential chroot dirs" _chroot_essential_dirs
    run_step "chroot_files"  "Populate /etc essentials" _chroot_etc_files
}

_mount_vfs() {
    mkdir -p "${LFS}"/{dev,proc,sys,run}

    # Bind mount /dev
    if ! mountpoint -q "${LFS}/dev"; then
        mount -v --bind /dev "${LFS}"/dev
    fi
    if ! mountpoint -q "${LFS}/dev/pts"; then
        mount -vt devpts devpts -o gid=5,mode=0620 "${LFS}"/dev/pts
    fi
    if ! mountpoint -q "${LFS}/proc"; then
        mount -vt proc proc "${LFS}"/proc
    fi
    if ! mountpoint -q "${LFS}/sys"; then
        mount -vt sysfs sysfs "${LFS}"/sys
    fi
    if ! mountpoint -q "${LFS}/run"; then
        mount -vt tmpfs tmpfs "${LFS}"/run
    fi
    if [[ -h "${LFS}/dev/shm" ]]; then
        mkdir -p "${LFS}/$(readlink "${LFS}"/dev/shm)"
    else
        if ! mountpoint -q "${LFS}/dev/shm"; then
            mount -vt tmpfs -o nosuid,nodev tmpfs "${LFS}"/dev/shm
        fi
    fi
}

_chroot_essential_dirs() {
    mkdir -p "${LFS}"/{etc,var} "${LFS}"/usr/{bin,lib,sbin}
    for i in bin lib sbin; do
        ln -sfn usr/"$i" "${LFS}/$i" 2>/dev/null || true
    done
    case "$(uname -m)" in
        x86_64) mkdir -p "${LFS}"/lib64 ;;
    esac
}

_chroot_etc_files() {
    # passwd / group
    cat > "${LFS}"/etc/passwd <<'EOF'
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF
    cat > "${LFS}"/etc/group <<'EOF'
root:x:0:
bin:x:1:root,bin,daemon
sys:x:2:root,bin,sys
kmem:x:3:root
tape:x:4:root
tty:x:5:root
daemon:x:6:root,bin,daemon
floppy:x:7:root
disk:x:8:root
lp:x:9:root,lp
dialout:x:10:root
audio:x:11:root
video:x:12:root,video
utmp:x:13:root
cdrom:x:15:root
adm:x:16:root,adm,daemon
messagebus:x:18:
input:x:24:root
mail:x:34:root
kvm:x:61:
uuidd:x:80:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF
    touch "${LFS}"/var/log/{btmp,lastlog,faillog,wtmp}
    chown -v root:utmp "${LFS}"/var/log/lastlog
    chmod -v 664 "${LFS}"/var/log/lastlog
    chmod -v 600 "${LFS}"/var/log/btmp
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 2 — CHROOT FINAL SYSTEM
# ─────────────────────────────────────────────────────────────────────────────
phase2_chroot_system() {
    banner "Phase 2 — Building Final System (chroot)"

    local CHROOT_SCRIPT="${LFS}/sources/flint_phase2.sh"
    _write_phase2_script "${CHROOT_SCRIPT}"
    chmod +x "${CHROOT_SCRIPT}"

    chroot "${LFS}" /usr/bin/env -i \
        HOME=/root                  \
        TERM="${TERM}"              \
        PS1='(flint chroot) \u:\w\$ ' \
        PATH=/usr/bin:/usr/sbin     \
        MAKEFLAGS="-j$(nproc)"      \
        CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt" \
        CXXFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt" \
        LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" \
        /bin/bash --login /sources/flint_phase2.sh
}

_write_phase2_script() {
    local script_path="$1"
    cat > "${script_path}" <<'CHROOT_SCRIPT'
#!/usr/bin/env bash
set -euo pipefail

NPROC=$(nproc)
SRC="/sources"
STATE="/flint_state"
LOGS="/flint_logs"
CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
MAKEFLAGS="-j${NPROC}"
export CFLAGS CXXFLAGS LDFLAGS MAKEFLAGS

step_done()    { mkdir -p "${STATE}"; touch "${STATE}/$1.done"; echo "  ✓ $1"; }
step_is_done() { [[ -f "${STATE}/$1.done" ]]; }
run_step() {
    local s="$1" d="$2"; shift 2
    step_is_done "${s}" && { echo "  → Skip: ${d}"; return 0; }
    echo "[P2] ${d}"
    mkdir -p "${LOGS}"
    "$@" 2>&1 | tee "${LOGS}/${s}.log"
    step_done "${s}"
}
extr() {
    cd /tmp
    rm -rf build_pkg 2>/dev/null; mkdir build_pkg; cd build_pkg
    tar xf "${SRC}/$1"
    cd "$(tar tf "${SRC}/$1" | head -1 | cut -d/ -f1)"
}

# ── Gettext (minimal) ─────────────────────────────────────────────────────
build_gettext() {
    extr "gettext-0.22.5.tar.xz" 2>/dev/null || {
        # Download inline if not present
        cd /tmp
        wget -q https://ftp.gnu.org/gnu/gettext/gettext-0.22.5.tar.xz -O "${SRC}/gettext-0.22.5.tar.xz"
        cd /tmp/build_pkg && tar xf "${SRC}/gettext-0.22.5.tar.xz"
        cd gettext-0.22.5
    }
    ./configure --disable-shared
    make -j"${NPROC}"
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
}
run_step "p2_gettext" "Gettext (minimal)" build_gettext

# ── Bison ─────────────────────────────────────────────────────────────────
build_bison() {
    cd /tmp; rm -rf bp; mkdir bp; cd bp
    wget -q https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz -O "${SRC}/bison-3.8.2.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/bison-3.8.2.tar.xz"; cd bison-3.8.2
    ./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2
    make -j"${NPROC}"; make install
}
run_step "p2_bison" "Bison" build_bison

# ── Perl (full) ───────────────────────────────────────────────────────────
build_perl() {
    extr "perl-5.38.2.tar.xz"
    sh Configure -des                         \
        -Dprefix=/usr                         \
        -Dvendorprefix=/usr                   \
        -Dprivlib=/usr/lib/perl5/5.38/core_perl    \
        -Darchlib=/usr/lib/perl5/5.38/core_perl    \
        -Dsitelib=/usr/lib/perl5/5.38/site_perl    \
        -Dsitearch=/usr/lib/perl5/5.38/site_perl   \
        -Dvendorlib=/usr/lib/perl5/5.38/vendor_perl \
        -Dvendorarch=/usr/lib/perl5/5.38/vendor_perl \
        -Dman1dir=/usr/share/man/man1         \
        -Dman3dir=/usr/share/man/man3         \
        -Dpager="/usr/bin/less -isR"          \
        -Duseshrplib                          \
        -Dusethreads
    make -j"${NPROC}"; make install
}
run_step "p2_perl" "Perl" build_perl

# ── Python ────────────────────────────────────────────────────────────────
build_python() {
    extr "Python-3.12.3.tar.xz"
    ./configure --prefix=/usr        \
                --enable-shared      \
                --with-system-expat  \
                --enable-optimizations
    make -j"${NPROC}"; make install
    ln -sfn python3 /usr/bin/python
    ln -sfn python3-config /usr/bin/python-config
}
run_step "p2_python" "Python 3.12" build_python

# ── Texinfo ───────────────────────────────────────────────────────────────
build_texinfo() {
    extr "texinfo-7.1.tar.xz"
    ./configure --prefix=/usr
    make -j"${NPROC}"; make install
}
run_step "p2_texinfo" "Texinfo" build_texinfo

# ── Util-linux ────────────────────────────────────────────────────────────
build_util_linux() {
    extr "util-linux-2.40.tar.xz"
    mkdir -pv /var/lib/hwclock
    ./configure --libdir=/usr/lib        \
                --runstatedir=/run       \
                --disable-chfn-chsh      \
                --disable-login          \
                --disable-nologin        \
                --disable-su             \
                --disable-setpriv        \
                --disable-runuser        \
                --disable-pylibmount     \
                --disable-static         \
                --disable-liblastlog2    \
                --without-python         \
                ADJTIME_PATH=/var/lib/hwclock/adjtime \
                --docdir=/usr/share/doc/util-linux-2.40
    make -j"${NPROC}"; make install
}
run_step "p2_util_linux" "Util-linux" build_util_linux

# ── Zlib ──────────────────────────────────────────────────────────────────
build_zlib() {
    extr "zlib-1.3.1.tar.gz"
    ./configure --prefix=/usr
    make -j"${NPROC}"; make install
    rm /usr/lib/libz.a
}
run_step "p2_zlib" "Zlib" build_zlib

# ── Bzip2 ─────────────────────────────────────────────────────────────────
build_bzip2() {
    extr "bzip2-1.0.8.tar.gz"
    sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
    sed -i "s|man/man1|share/man/man1|g" Makefile
    make -f Makefile-libbz2_so CFLAGS="${CFLAGS} -fPIC"
    make clean
    make -j"${NPROC}" PREFIX=/usr install
    cp -av libbz2.so.* /usr/lib
    ln -sv libbz2.so.1.0.8 /usr/lib/libbz2.so
    install -dm755 /usr/lib/pkgconfig
}
run_step "p2_bzip2" "Bzip2" build_bzip2

# ── Xz (final) ────────────────────────────────────────────────────────────
build_xz_final() {
    extr "xz-5.4.6.tar.xz"
    ./configure --prefix=/usr          \
                --disable-static       \
                --docdir=/usr/share/doc/xz-5.4.6
    make -j"${NPROC}"; make install
}
run_step "p2_xz" "Xz (final)" build_xz_final

# ── Zstd ──────────────────────────────────────────────────────────────────
build_zstd() {
    extr "zstd-1.5.6.tar.gz"
    make -j"${NPROC}" prefix=/usr
    make prefix=/usr install
    rm /usr/lib/libzstd.a
}
run_step "p2_zstd" "Zstd" build_zstd

# ── OpenSSL ───────────────────────────────────────────────────────────────
build_openssl() {
    extr "openssl-3.3.0.tar.gz"
    ./config --prefix=/usr         \
             --openssldir=/etc/ssl \
             --libdir=lib          \
             shared                \
             zlib-dynamic
    make -j"${NPROC}"; make install
    sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
}
run_step "p2_openssl" "OpenSSL" build_openssl

# ── Kmod ──────────────────────────────────────────────────────────────────
build_kmod() {
    extr "kmod-32.tar.xz"
    ./configure --prefix=/usr       \
                --sysconfdir=/etc   \
                --with-openssl      \
                --with-xz           \
                --with-zstd         \
                --with-zlib
    make -j"${NPROC}"; make install
    for target in depmod insmod modinfo modprobe rmmod; do
        ln -sfv ../bin/kmod /usr/sbin/$target
    done
    ln -sfv kmod /usr/bin/lsmod
}
run_step "p2_kmod" "Kmod" build_kmod

# ── Libcap ────────────────────────────────────────────────────────────────
build_libcap() {
    extr "libcap-2.70.tar.xz"
    sed -i '/install -m.*STA/d' libcap/Makefile
    make prefix=/usr lib=lib
    make prefix=/usr lib=lib install
}
run_step "p2_libcap" "Libcap" build_libcap

# ── Shadow ────────────────────────────────────────────────────────────────
build_shadow() {
    extr "shadow-4.15.1.tar.xz"
    sed -i 's/groups$(EXEEXT) //' src/Makefile.in
    find man -name 'groups.1' -delete
    sed -i 's/\(^#ENCRYPT_METHOD \).*/\1SHA512/' etc/login.defs
    sed -i 's@#\(MAIL_DIR\).*@\1\t\t/var/mail@' etc/login.defs
    touch /usr/bin/passwd
    ./configure --sysconfdir=/etc     \
                --disable-static      \
                --with-{b,yes}crypt   \
                --without-libbsd      \
                --with-group-name-max-length=32
    make -j"${NPROC}"; make exec_prefix=/usr install
    make -C man install-man
    pwconv; grpconv
    # Set root password to 'flint' (change after install!)
    echo "root:flint" | chpasswd
}
run_step "p2_shadow" "Shadow" build_shadow

# ── Readline ──────────────────────────────────────────────────────────────
build_readline() {
    extr "readline-8.2.tar.gz"
    sed -i '/MV.*old/d' Makefile.in
    sed -i '/{OLDSUFF}/c:' support/shlib-install
    sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf
    ./configure --prefix=/usr \
                --disable-static \
                --with-curses    \
                --docdir=/usr/share/doc/readline-8.2
    make SHLIB_LIBS="-lncursesw" -j"${NPROC}"
    make SHLIB_LIBS="-lncursesw" install
    install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.2
}
run_step "p2_readline" "Readline" build_readline

# ── Bash (final) ──────────────────────────────────────────────────────────
build_bash_final() {
    extr "bash-5.2.21.tar.gz"
    ./configure --prefix=/usr           \
                --without-bash-malloc   \
                --with-installed-readline \
                --docdir=/usr/share/doc/bash-5.2.21
    make -j"${NPROC}"
    make install
    ln -sfn bash /usr/bin/sh
}
run_step "p2_bash" "Bash (final)" build_bash_final

# ── Ncurses (final) ───────────────────────────────────────────────────────
build_ncurses_final() {
    extr "ncurses-6.5.tar.gz"
    ./configure --prefix=/usr           \
                --mandir=/usr/share/man \
                --with-shared           \
                --without-debug         \
                --without-normal        \
                --with-cxx-shared       \
                --enable-pc-files       \
                --with-pkg-config-libdir=/usr/lib/pkgconfig \
                --enable-widec
    make -j"${NPROC}"; make install
    for lib in ncurses form panel menu; do
        ln -sfv lib${lib}w.so /usr/lib/lib${lib}.so
        ln -sfv ${lib}w.pc    /usr/lib/pkgconfig/${lib}.pc
    done
    ln -sfv libncursesw.so /usr/lib/libcurses.so
}
run_step "p2_ncurses" "Ncurses (final)" build_ncurses_final

# ── Coreutils (final) ─────────────────────────────────────────────────────
build_coreutils_final() {
    extr "coreutils-9.5.tar.xz"
    autoreconf -fiv 2>/dev/null || true
    FORCE_UNSAFE_CONFIGURE=1 ./configure \
        --prefix=/usr             \
        --enable-no-install-program=kill,uptime
    make -j"${NPROC}"; make install
    mv -v /usr/bin/chroot /usr/sbin
}
run_step "p2_coreutils" "Coreutils (final)" build_coreutils_final

# ── Less ──────────────────────────────────────────────────────────────────
build_less() {
    extr "less-661.tar.gz"
    ./configure --prefix=/usr --sysconfdir=/etc
    make -j"${NPROC}"; make install
}
run_step "p2_less" "Less" build_less

# ── Grep / Sed / Gawk / Gzip / Tar / Make / Patch / Diffutils / Findutils ─
for pkg in \
    "grep-3.11.tar.xz:./configure --prefix=/usr" \
    "sed-4.9.tar.xz:./configure --prefix=/usr" \
    "gawk-5.3.0.tar.xz:./configure --prefix=/usr" \
    "gzip-1.13.tar.xz:./configure --prefix=/usr" \
    "tar-1.35.tar.xz:./configure --prefix=/usr" \
    "make-4.4.1.tar.gz:./configure --prefix=/usr" \
    "patch-2.7.6.tar.xz:./configure --prefix=/usr" \
    "diffutils-3.10.tar.xz:./configure --prefix=/usr" \
    "findutils-4.9.0.tar.xz:./configure --prefix=/usr --localstatedir=/var/lib/locate"
do
    tarball="${pkg%%:*}"
    confcmd="${pkg##*:}"
    pkgname="${tarball%%-[0-9]*}"
    step_id="p2_${pkgname//-/_}"
    build_simple_pkg() {
        extr "${tarball}"
        eval "${confcmd}"
        make -j"${NPROC}"; make install
    }
    run_step "${step_id}" "${pkgname} (final)" build_simple_pkg
done

# ── Procps-ng ─────────────────────────────────────────────────────────────
build_procps() {
    extr "procps-ng-4.0.4.tar.xz"
    ./configure --prefix=/usr                \
                --docdir=/usr/share/doc/procps-ng-4.0.4 \
                --disable-static             \
                --disable-kill               \
                --with-systemd=no
    make -j"${NPROC}"; make install
}
run_step "p2_procps" "Procps-ng" build_procps

# ── E2fsprogs ─────────────────────────────────────────────────────────────
build_e2fsprogs() {
    extr "e2fsprogs-1.47.1.tar.gz"
    mkdir -v build && cd build
    ../configure --prefix=/usr           \
                 --sysconfdir=/etc        \
                 --enable-elf-shlibs      \
                 --disable-libblkid       \
                 --disable-libuuid        \
                 --disable-uuidd          \
                 --disable-fsck
    make -j"${NPROC}"; make install
    rm /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
}
run_step "p2_e2fsprogs" "E2fsprogs" build_e2fsprogs

# ── Iproute2 ──────────────────────────────────────────────────────────────
build_iproute2() {
    extr "iproute2-6.9.0.tar.xz"
    sed -i /ARPD/d Makefile
    rm -fv man/man8/arpd.8
    make NETNS_RUN_DIR=/run/netns -j"${NPROC}"
    make SBINDIR=/usr/sbin install
}
run_step "p2_iproute2" "Iproute2" build_iproute2

# ── Vim ───────────────────────────────────────────────────────────────────
build_vim() {
    cd /tmp; rm -rf build_vim; mkdir build_vim; cd build_vim
    wget -q "https://github.com/vim/vim/archive/refs/tags/v9.1.0.tar.gz" \
        -O "${SRC}/vim-9.1.0.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/vim-9.1.0.tar.gz"; cd vim-9.1.0
    echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
    ./configure --prefix=/usr
    make -j"${NPROC}"; make install
    ln -sfv vim /usr/bin/vi
    cat > /etc/vimrc <<'VIMRC'
set nocompatible
set backspace=2
set mouse=
syntax on
set number
set tabstop=4 shiftwidth=4 expandtab
colorscheme desert
VIMRC
}
run_step "p2_vim" "Vim" build_vim

# ─────────────────────────────────────────────────────────────────────────────
# LINUX KERNEL — 6.9.3 with Skylake + i915 + zram
# ─────────────────────────────────────────────────────────────────────────────
build_kernel() {
    extr "linux-6.9.3.tar.xz"
    make mrproper

    # Base config (allmodconfig trimmed to minimal)
    make defconfig

    # Apply Flint-specific config via script
    cat >> .config <<'KCONF'
# Skylake CPU optimizations
CONFIG_MSKYLAKE=y
CONFIG_MNATIVE_INTEL=n
CONFIG_GENERIC_CPU=n

# Processor features
CONFIG_X86_64=y
CONFIG_SMP=y
CONFIG_NR_CPUS=4
CONFIG_HZ_1000=y
CONFIG_HZ=1000
CONFIG_PREEMPT=y
CONFIG_NO_HZ_FULL=y
CONFIG_RCU_NOCB_CPU=y

# Intel i915 (HD Graphics 520) — built-in
CONFIG_DRM=y
CONFIG_DRM_I915=y
CONFIG_DRM_I915_USERPTR=y
CONFIG_DRM_KMS_HELPER=y
CONFIG_DRM_KMS_FB_HELPER=y
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_FB=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_DRM_I915_GVT=n

# Display output
CONFIG_DRM_DP_AUX_CHARDEV=y
CONFIG_DRM_DISPLAY_DP_HELPER=y
CONFIG_DRM_DISPLAY_HDMI_HELPER=y

# Display connector (ThinkPad T460: eDP + HDMI + miniDP)
CONFIG_DRM_I915_FORCE_PROBE="*"

# Zram (compressed RAM block device)
CONFIG_ZRAM=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
CONFIG_ZSMALLOC=y
CONFIG_CRYPTO_LZ4=y
CONFIG_CRYPTO_LZ4HC=y
CONFIG_CRYPTO_ZSTD=y

# Filesystem support
CONFIG_EXT4_FS=y
CONFIG_BTRFS_FS=y
CONFIG_XFS_FS=y
CONFIG_VFAT_FS=y
CONFIG_TMPFS=y
CONFIG_TMPFS_POSIX_ACL=y

# Network
CONFIG_NET=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_WIRELESS=y
CONFIG_CFG80211=y
CONFIG_MAC80211=y
CONFIG_IWLWIFI=y
CONFIG_IWLMVM=y
CONFIG_RFKILL=y

# Ethernet (ThinkPad T460 — Intel I219-LM)
CONFIG_E1000E=y
CONFIG_IGB=n

# USB / Input
CONFIG_USB=y
CONFIG_USB_XHCI_HCD=y
CONFIG_USB_EHCI_HCD=y
CONFIG_INPUT=y
CONFIG_INPUT_KEYBOARD=y
CONFIG_INPUT_MOUSE=y
CONFIG_KEYBOARD_ATKBD=y
CONFIG_MOUSE_PS2=y
CONFIG_MOUSE_PS2_ELANTECH=y
CONFIG_HID=y
CONFIG_USB_HID=y

# Power management (laptop)
CONFIG_ACPI=y
CONFIG_ACPI_BATTERY=y
CONFIG_ACPI_AC=y
CONFIG_ACPI_BUTTON=y
CONFIG_ACPI_FAN=y
CONFIG_ACPI_THERMAL=y
CONFIG_INTEL_IDLE=y
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
CONFIG_X86_INTEL_PSTATE=y
CONFIG_INTEL_TURBO_BOOST=y

# ThinkPad extras
CONFIG_THINKPAD_ACPI=y
CONFIG_BACKLIGHT_CLASS_DEVICE=y
CONFIG_BACKLIGHT_INTEL_PANEL=y

# Sound (Intel HDA — ThinkPad T460)
CONFIG_SND=y
CONFIG_SND_HDA_INTEL=y
CONFIG_SND_HDA_CODEC_REALTEK=y
CONFIG_SND_HDA_CODEC_HDMI=y

# Security
CONFIG_SECURITY=y
CONFIG_SECURITY_SELINUX=n
CONFIG_SECURITY_APPARMOR=y
CONFIG_DEFAULT_SECURITY_APPARMOR=y

# Init RAM disk
CONFIG_BLK_DEV_INITRD=y
CONFIG_INITRAMFS_SOURCE=""
CONFIG_RD_GZIP=y
CONFIG_RD_BZIP2=y
CONFIG_RD_XZ=y
CONFIG_RD_LZO=y
CONFIG_RD_LZ4=y
CONFIG_RD_ZSTD=y

# Block
CONFIG_BLK_DEV_SD=y
CONFIG_BLK_DEV_SR=y
CONFIG_SCSI=y
CONFIG_ATA=y
CONFIG_SATA_AHCI=y
CONFIG_ATA_PIIX=y
CONFIG_NVMe_CORE=y
CONFIG_BLK_DEV_NVME=y

# Misc
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
CONFIG_DMIID=y
CONFIG_EXPERT=n
KCONF

    # Resolve config deps
    make olddefconfig

    # Build with Skylake-tuned CFLAGS (kernel has its own flag handling)
    make KCFLAGS="-march=skylake -mtune=skylake -O2 -pipe" \
         -j"${NPROC}" bzImage modules

    make modules_install

    # Install kernel and initrd location
    install -v -m755 arch/x86/boot/bzImage /boot/vmlinuz-6.9.3-flint
    install -v -m644 System.map /boot/System.map-6.9.3
    install -v -m644 .config /boot/config-6.9.3

    # Copy headers for out-of-tree modules
    make headers_install INSTALL_HDR_PATH=/usr
}
run_step "p2_kernel" "Linux Kernel 6.9.3" build_kernel

# ─────────────────────────────────────────────────────────────────────────────
# DINIT — Minimal, fast init system
# ─────────────────────────────────────────────────────────────────────────────
build_dinit() {
    extr "dinit-0.19.1.tar.gz"
    make -j"${NPROC}"           \
        CXXFLAGS="${CXXFLAGS}"  \
        LDFLAGS="${LDFLAGS}"    \
        SBINDIR=/usr/sbin       \
        SYSCONTROLSOCKET=/run/dinitctl
    make install SBINDIR=/usr/sbin
    install -dm755 /etc/dinit.d

    # System service definitions
    cat > /etc/dinit.d/boot <<'DINIT_BOOT'
type = scripted
command = /etc/dinit.d/scripts/boot.sh
logfile = /var/log/dinit/boot.log
DINIT_BOOT

    cat > /etc/dinit.d/login.getty <<'DINIT_GETTY'
type = process
command = /sbin/agetty --autologin flint --noclear tty1 linux
restart = true
logfile = /var/log/dinit/getty.log
DINIT_GETTY

    cat > /etc/dinit.d/sshd <<'DINIT_SSHD'
type = process
command = /usr/sbin/sshd -D
restart = true
DINIT_SSHD

    cat > /etc/dinit.d/networking <<'DINIT_NET'
type = scripted
command = /etc/dinit.d/scripts/networking.sh
DINIT_NET

    mkdir -p /etc/dinit.d/scripts /var/log/dinit

    cat > /etc/dinit.d/scripts/boot.sh <<'BOOT_SH'
#!/bin/bash
# Flint Linux boot sequence
mount -o remount,rw /
mount -a
swapon -a

# Hostname
echo "flint" > /proc/sys/kernel/hostname

# Locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# System clock
hwclock --hctosys 2>/dev/null || true

# Activate zram swap
modprobe zram
echo lz4 > /sys/block/zram0/comp_algorithm
echo 4G  > /sys/block/zram0/disksize
mkswap /dev/zram0
swapon -p 100 /dev/zram0

# Kernel tunables for performance
sysctl -w vm.swappiness=10
sysctl -w vm.vfs_cache_pressure=50
sysctl -w kernel.nmi_watchdog=0
sysctl -w net.core.netdev_max_backlog=16384
BOOT_SH
    chmod +x /etc/dinit.d/scripts/boot.sh

    cat > /etc/dinit.d/scripts/networking.sh <<'NET_SH'
#!/bin/bash
ip link set lo up
# DHCP on first ethernet (adjust interface name post-boot)
ip link set eth0 up 2>/dev/null || true
dhcpcd eth0 2>/dev/null || true
NET_SH
    chmod +x /etc/dinit.d/scripts/networking.sh

    # Link dinit as /sbin/init
    ln -sfv /usr/sbin/dinit /sbin/init
}
run_step "p2_dinit" "Dinit init system" build_dinit

# ─────────────────────────────────────────────────────────────────────────────
# PACMAN BOOTSTRAP
# ─────────────────────────────────────────────────────────────────────────────
build_pacman() {
    # Dependencies: libarchive, curl, gpgme
    cd /tmp; rm -rf pacman_deps; mkdir pacman_deps; cd pacman_deps

    # libarchive
    wget -q https://www.libarchive.org/downloads/libarchive-3.7.4.tar.xz \
        -O "${SRC}/libarchive-3.7.4.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/libarchive-3.7.4.tar.xz"; cd libarchive-3.7.4
    ./configure --prefix=/usr --disable-static --without-xml2
    make -j"${NPROC}"; make install; cd ..

    # curl
    wget -q https://curl.se/download/curl-8.8.0.tar.xz \
        -O "${SRC}/curl-8.8.0.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/curl-8.8.0.tar.xz"; cd curl-8.8.0
    ./configure --prefix=/usr          \
                --with-openssl         \
                --enable-threaded-resolver \
                --disable-static
    make -j"${NPROC}"; make install; cd ..

    # fakeroot (for makepkg)
    wget -q https://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.36.orig.tar.gz \
        -O "${SRC}/fakeroot_1.36.orig.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/fakeroot_1.36.orig.tar.gz" 2>/dev/null || true
    ls -la; cd fakeroot-1.36 2>/dev/null || cd fakeroot*/
    ./configure --prefix=/usr --libdir=/usr/lib/libfakeroot \
                --with-ipc=sysv
    make -j"${NPROC}"; make install; cd ..

    # pacman itself
    extr "pacman-6.1.0.tar.xz"
    meson setup build              \
        --prefix=/usr              \
        --buildtype=release        \
        -Db_lto=true               \
        -Duse-git-version=false    \
        -Dscriptlet-shell=/usr/bin/bash \
        -Dldconfig=/usr/bin/ldconfig
    ninja -C build -j"${NPROC}"
    ninja -C build install

    # Pacman configuration
    mkdir -p /etc/pacman.d /var/lib/pacman /var/cache/pacman/pkg /var/log

    cat > /etc/pacman.conf <<'PACMAN_CONF'
[options]
HoldPkg     = pacman glibc
Architecture = x86_64

Color
ParallelDownloads = 5
ILoveCandy

CheckSpace
VerbosePkgLists

SigLevel    = Never
LocalFileSigLevel = Optional

[flint]
Server = file:///var/cache/pacman/flint/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
PACMAN_CONF

    cat > /etc/pacman.d/mirrorlist <<'MIRRORLIST'
# Flint Linux — Arch Linux mirrors for bootstrapped packages
Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
MIRRORLIST

    # makepkg config with Skylake optimizations
    cat > /etc/makepkg.conf <<'MAKEPKG_CONF'
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt"
CXXFLAGS="$CFLAGS"
RUSTFLAGS="-C opt-level=2 -C target-cpu=skylake"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
MAKEFLAGS="-j$(nproc)"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="-g"
DEBUG_RUSTFLAGS="-C debuginfo=1"

BUILDENV=(!distcc color !ccache check !sign)
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
INTEGRITY_CHECK=(sha256)
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"

PKGDEST=/var/cache/pacman/pkg
SRCDEST=/var/cache/pacman/src
LOGDEST=/var/log/pacman/makepkg
PACKAGER="Flint Linux Builder"
GPGKEY=""

COMPRESSGZ=(gzip -c -f -n)
COMPRESSBZ2=(bzip2 -c -f)
COMPRESSXZ=(xz -c -z --threads=0 -)
COMPRESSZST=(zstd -c -z -q --threads=0 -)
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'
MAKEPKG_CONF

    # Initialize pacman DB
    pacman-db-upgrade 2>/dev/null || true
    pacman-key --init 2>/dev/null || true
}
run_step "p2_pacman" "Pacman package manager" build_pacman

# ── System configuration ──────────────────────────────────────────────────
configure_system() {
    # Hostname
    echo "flint" > /etc/hostname

    # Hosts
    cat > /etc/hosts <<'EOF'
127.0.0.1  localhost
127.0.1.1  flint.localdomain flint
::1        localhost ip6-localhost ip6-loopback
ff02::1    ip6-allnodes
ff02::2    ip6-allrouters
EOF

    # fstab (placeholder — user must customize)
    cat > /etc/fstab <<'EOF'
# <file system>  <mount point>  <type>    <options>              <dump>  <pass>
# Edit with your actual device names (lsblk to find them)
/dev/sda2        /              ext4      defaults,noatime        0       1
/dev/sda1        /boot          vfat      umask=0077              0       2
/dev/sda3        none           swap      sw                      0       0
tmpfs            /tmp           tmpfs     defaults,noatime,mode=1777  0   0
EOF

    # Profile / environment
    cat > /etc/profile <<'EOF'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color
export EDITOR=vim
export VISUAL=vim
export PAGER=less
export BROWSER=firefox
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

# Skylake CPU tuning via env
export CFLAGS="-march=skylake -mtune=skylake -O2 -pipe -fno-plt"
export CXXFLAGS="${CFLAGS}"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

for script in /etc/profile.d/*.sh; do
    [ -r "$script" ] && source "$script"
done
EOF

    # Locale
    cat > /etc/locale.gen <<'EOF'
en_US.UTF-8 UTF-8
EOF
    cat > /etc/locale.conf <<'EOF'
LANG=en_US.UTF-8
LC_COLLATE=C.UTF-8
EOF
    locale-gen 2>/dev/null || true

    # ld.so.conf
    cat > /etc/ld.so.conf <<'EOF'
/usr/local/lib
/usr/lib
include /etc/ld.so.conf.d/*.conf
EOF
    mkdir -p /etc/ld.so.conf.d
    ldconfig

    # sysctl tweaks (Skylake / laptop optimizations)
    cat > /etc/sysctl.d/99-flint.conf <<'EOF'
# Memory
vm.swappiness = 10
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5

# Network
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 8192
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_ecn = 1
net.ipv4.tcp_timestamps = 0

# Misc
kernel.nmi_watchdog = 0
kernel.unprivileged_userns_clone = 1
EOF

    # Create main user
    useradd -m -G wheel,audio,video,input,kvm -s /bin/bash flint 2>/dev/null || true
    echo "flint:flint" | chpasswd
    echo "%wheel ALL=(ALL:ALL) ALL" >> /etc/sudoers

    # Sudoers
    cat > /etc/sudoers.d/wheel <<'EOF'
%wheel ALL=(ALL:ALL) ALL
EOF
    chmod 440 /etc/sudoers.d/wheel
}
run_step "p2_sysconfig" "System configuration" configure_system

# ── Wayland stack dependencies ─────────────────────────────────────────────
install_wayland_deps() {
    cd /tmp; rm -rf wayland_build; mkdir wayland_build; cd wayland_build

    # wayland
    wget -q https://gitlab.freedesktop.org/wayland/wayland/-/releases/1.23.0/downloads/wayland-1.23.0.tar.xz \
        -O "${SRC}/wayland-1.23.0.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/wayland-1.23.0.tar.xz"; cd wayland-1.23.0
    meson setup build --prefix=/usr --buildtype=release -Ddocumentation=false
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..

    # wayland-protocols
    wget -q https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/1.36/downloads/wayland-protocols-1.36.tar.xz \
        -O "${SRC}/wayland-protocols-1.36.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/wayland-protocols-1.36.tar.xz"; cd wayland-protocols-1.36
    meson setup build --prefix=/usr --buildtype=release
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..

    # libxkbcommon
    wget -q https://xkbcommon.org/download/libxkbcommon-1.7.0.tar.xz \
        -O "${SRC}/libxkbcommon-1.7.0.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/libxkbcommon-1.7.0.tar.xz"; cd libxkbcommon-1.7.0
    meson setup build --prefix=/usr --buildtype=release -Denable-docs=false
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..

    # libinput
    wget -q https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.26.0/libinput-1.26.0.tar.gz \
        -O "${SRC}/libinput-1.26.0.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/libinput-1.26.0.tar.gz"; cd libinput-1.26.0
    meson setup build --prefix=/usr --buildtype=release \
        -Ddocumentation=false -Dtests=false -Ddebug-gui=false
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..

    # pixman
    wget -q https://cairographics.org/releases/pixman-0.43.4.tar.gz \
        -O "${SRC}/pixman-0.43.4.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/pixman-0.43.4.tar.gz"; cd pixman-0.43.4
    meson setup build --prefix=/usr --buildtype=release
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..

    # mesa (needed for GPU accel / DRI)
    wget -q https://mesa.freedesktop.org/archive/mesa-24.1.2.tar.xz \
        -O "${SRC}/mesa-24.1.2.tar.xz" 2>/dev/null || true
    tar xf "${SRC}/mesa-24.1.2.tar.xz"; cd mesa-24.1.2
    meson setup build --prefix=/usr --buildtype=release         \
        -Dgallium-drivers=iris,crocus                           \
        -Dvulkan-drivers=intel                                   \
        -Dplatforms=wayland                                      \
        -Degl=enabled -Dgles2=enabled                            \
        -Dopengl=true                                            \
        -Dglx=disabled                                           \
        -Dllvm=disabled                                          \
        -Dshared-glapi=enabled                                   \
        -Dvideo-codecs=all
    ninja -C build -j"${NPROC}"; ninja -C build install; cd ..
}
run_step "p2_wayland_deps" "Wayland stack + Mesa" install_wayland_deps

# ── Hyprland ──────────────────────────────────────────────────────────────
build_hyprland() {
    cd /tmp; rm -rf hypr_build; mkdir hypr_build; cd hypr_build

    # hyprutils
    git clone --depth=1 https://github.com/hyprwm/hyprutils.git 2>/dev/null || \
        wget -q https://github.com/hyprwm/hyprutils/archive/refs/heads/main.tar.gz \
             -O "${SRC}/hyprutils.tar.gz" && tar xf "${SRC}/hyprutils.tar.gz"
    cd hyprutils* || cd hyprutils
    cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_CXX_FLAGS="${CXXFLAGS}"
    cmake --build build -j"${NPROC}"; cmake --install build; cd ..

    # aquamarine (backend)
    git clone --depth=1 https://github.com/hyprwm/aquamarine.git 2>/dev/null || \
        wget -q https://github.com/hyprwm/aquamarine/archive/refs/heads/main.tar.gz \
             -O "${SRC}/aquamarine.tar.gz" && tar xf "${SRC}/aquamarine.tar.gz"
    cd aquamarine* || cd aquamarine
    cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_CXX_FLAGS="${CXXFLAGS}"
    cmake --build build -j"${NPROC}"; cmake --install build; cd ..

    # Hyprland itself
    wget -q "https://github.com/hyprwm/Hyprland/releases/download/v${HYPRLAND_VERSION}/source-v${HYPRLAND_VERSION}.tar.gz" \
        -O "${SRC}/hyprland-${HYPRLAND_VERSION}.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/hyprland-${HYPRLAND_VERSION}.tar.gz" 2>/dev/null || \
        git clone --depth=1 --recurse-submodules https://github.com/hyprwm/Hyprland.git
    cd Hyprland* 2>/dev/null || cd hyprland*
    cmake -B build                                \
        -DCMAKE_BUILD_TYPE=Release                \
        -DCMAKE_INSTALL_PREFIX=/usr               \
        -DCMAKE_C_FLAGS="${CFLAGS}"               \
        -DCMAKE_CXX_FLAGS="${CXXFLAGS}"           \
        -DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}"     \
        -DHYPRLAND_VERSION="${HYPRLAND_VERSION}"  \
        -DUSE_SYSTEM_WLROOTS=OFF                  \
        -DINSTALL_IPC_SERVER=ON
    cmake --build build -j"${NPROC}"
    cmake --install build
}
run_step "p2_hyprland" "Hyprland compositor" build_hyprland

# ── Waybar ────────────────────────────────────────────────────────────────
build_waybar() {
    cd /tmp; rm -rf waybar_build; mkdir waybar_build; cd waybar_build
    wget -q "https://github.com/Alexays/Waybar/archive/refs/tags/${WAYBAR_VERSION}.tar.gz" \
        -O "${SRC}/waybar-${WAYBAR_VERSION}.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/waybar-${WAYBAR_VERSION}.tar.gz" 2>/dev/null || \
        git clone --depth=1 https://github.com/Alexays/Waybar.git
    cd Waybar* 2>/dev/null || cd waybar*
    meson setup build                     \
        --prefix=/usr                     \
        --buildtype=release               \
        -Dsystemd=disabled                \
        -Dpulseaudio=disabled             \
        -Dpipewire=disabled               \
        -Dmpd=disabled                    \
        -Dlibudev=enabled                 \
        -Dlibnl=enabled                   \
        -Dgtk-layer-shell=enabled
    ninja -C build -j"${NPROC}"
    ninja -C build install
}
run_step "p2_waybar" "Waybar status bar" build_waybar

# ── Foot terminal ─────────────────────────────────────────────────────────
build_foot() {
    cd /tmp; rm -rf foot_build; mkdir foot_build; cd foot_build
    wget -q "https://codeberg.org/dnkl/foot/releases/download/${FOOT_VERSION}/foot-${FOOT_VERSION}.tar.gz" \
        -O "${SRC}/foot-${FOOT_VERSION}.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/foot-${FOOT_VERSION}.tar.gz" 2>/dev/null || \
        git clone --depth=1 https://codeberg.org/dnkl/foot.git
    cd foot* 2>/dev/null || cd foot
    meson setup build          \
        --prefix=/usr          \
        --buildtype=release    \
        -Db_lto=true           \
        -Db_pgo=generate       \
        -Dime=true             \
        -Dgrapheme-clustering=enabled
    ninja -C build -j"${NPROC}"
    ninja -C build install
}
run_step "p2_foot" "Foot terminal" build_foot

# ── Fastfetch ─────────────────────────────────────────────────────────────
build_fastfetch() {
    cd /tmp; rm -rf ff_build; mkdir ff_build; cd ff_build
    wget -q "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/${FASTFETCH_VERSION}.tar.gz" \
        -O "${SRC}/fastfetch-${FASTFETCH_VERSION}.tar.gz" 2>/dev/null || true
    tar xf "${SRC}/fastfetch-${FASTFETCH_VERSION}.tar.gz"
    cd fastfetch-${FASTFETCH_VERSION}
    cmake -B build                             \
        -DCMAKE_BUILD_TYPE=Release             \
        -DCMAKE_INSTALL_PREFIX=/usr            \
        -DCMAKE_C_FLAGS="${CFLAGS}"            \
        -DENABLE_EMBEDDED_PCIIDS=ON            \
        -DENABLE_VULKAN=OFF
    cmake --build build -j"${NPROC}"
    cmake --install build
}
run_step "p2_fastfetch" "Fastfetch" build_fastfetch

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Phase 2 Complete — Final system built!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
CHROOT_SCRIPT
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 3 — POST-INSTALL (bootloader, dotfiles, configs)
# ─────────────────────────────────────────────────────────────────────────────
phase3_postinstall() {
    banner "Phase 3 — Post-Install (bootloader + desktop config)"

    run_step "p3_grub"       "Install GRUB bootloader"      _install_grub
    run_step "p3_hypr_cfg"   "Hyprland configuration"       _configure_hyprland
    run_step "p3_waybar_cfg" "Waybar configuration"         _configure_waybar
    run_step "p3_foot_cfg"   "Foot terminal configuration"  _configure_foot
    run_step "p3_fastfetch"  "Fastfetch configuration"      _configure_fastfetch
    run_step "p3_zram_svc"   "Zram dinit service"           _configure_zram_service
    run_step "p3_finalize"   "System finalization"          _finalize_system
}

_install_grub() {
    # Install GRUB source and build inside chroot
    chroot "${LFS}" /usr/bin/env -i HOME=/root PATH=/usr/bin:/usr/sbin \
        bash -c '
        cd /tmp
        wget -q https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz \
            -O /sources/grub-2.12.tar.xz 2>/dev/null || true
        mkdir -p grub_build; cd grub_build
        tar xf /sources/grub-2.12.tar.xz; cd grub-2.12

        # Unicode font
        wget -q https://unifoundry.com/pub/unifont/unifont-15.1.04/font-builds/unifont-15.1.04.pcf.gz \
            -O /sources/unifont-15.1.04.pcf.gz 2>/dev/null || true

        unset {C,CPP,CXX,LD}FLAGS
        ./configure --prefix=/usr            \
                    --sysconfdir=/etc         \
                    --disable-efiemu          \
                    --disable-werror

        make -j"$(nproc)"
        make install

        # GRUB config
        mkdir -p /boot/grub
        cat > /etc/default/grub <<'"'"'GRUB_DEFAULTS'"'"'
GRUB_DEFAULT=0
GRUB_TIMEOUT=3
GRUB_TIMEOUT_STYLE=menu
GRUB_DISTRIBUTOR="Flint Linux"
GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 nowatchdog page_alloc.shuffle=1 mitigations=auto,nosmt"
GRUB_CMDLINE_LINUX="rootwait"
GRUB_GFXMODE=auto
GRUB_GFXPAYLOAD_LINUX=keep
GRUB_DISABLE_RECOVERY=true
GRUB_DISABLE_OS_PROBER=false
GRUB_DEFAULTS

        # NOTE: grub-install must be run manually with the correct disk device
        # e.g.:  grub-install --target=x86_64-efi --efi-directory=/boot/efi
        #    or: grub-install --target=i386-pc /dev/sda
        # Then:  grub-mkconfig -o /boot/grub/grub.cfg
        echo "GRUB installed. Run grub-install manually for your disk/EFI setup."
    '
}

_configure_hyprland() {
    local hypr_cfg_dir="${LFS}/home/flint/.config/hypr"
    mkdir -p "${hypr_cfg_dir}"

    cat > "${hypr_cfg_dir}/hyprland.conf" <<'EOF'
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Flint Linux — Hyprland Configuration
#  Hardware: ThinkPad T460, i7-6600U, Intel HD 520
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ── Monitors ──────────────────────────────────────────
# ThinkPad T460 internal display (1920x1080@60Hz)
monitor=eDP-1,1920x1080@60,0x0,1

# External monitor (auto-detect, right of laptop)
monitor=,preferred,auto,1

# ── GPU (Intel HD 520 / Skylake GT2) ──────────────────
env = WLR_DRM_DEVICES,/dev/dri/card0
env = __GLX_VENDOR_LIBRARY_NAME,mesa
env = MESA_LOADER_DRIVER_OVERRIDE,iris
env = WLR_RENDERER,gles2

# ── Wayland / XDG ─────────────────────────────────────
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11

# ── Input ─────────────────────────────────────────────
input {
    kb_layout = us
    kb_options = caps:escape

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = yes
        tap-to-click = yes
        drag_lock = yes
        middle_button_emulation = yes
        scroll_factor = 0.5
    }

    accel_profile = adaptive
}

# ── General ───────────────────────────────────────────
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(88c0d0) rgb(5e81ac) 45deg
    col.inactive_border = rgb(3b4252)
    layout = dwindle
    allow_tearing = false
}

# ── Decorations ───────────────────────────────────────
decoration {
    rounding = 8
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
        xray = false
    }
    active_opacity = 1.0
    inactive_opacity = 0.92
    drop_shadow = true
    shadow_range = 12
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

# ── Animations ────────────────────────────────────────
animations {
    enabled = yes
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = smoothIn, 0.25, 1, 0.5, 1

    animation = windows, 1, 5, overshot, slide
    animation = windowsOut, 1, 4, smoothIn, popin 80%
    animation = fade, 1, 4, smoothIn
    animation = workspaces, 1, 5, overshot, slidefade 20%
    animation = specialWorkspace, 1, 5, overshot, slidefadevert 20%
}

# ── Layout ────────────────────────────────────────────
dwindle {
    pseudotile = yes
    preserve_split = yes
    smart_split = true
    smart_resizing = true
}

master {
    new_is_master = false
}

gestures {
    workspace_swipe = on
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
}

# ── Misc ──────────────────────────────────────────────
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    enable_swallow = true
    swallow_regex = ^(foot|alacritty)$
    key_press_enables_dpms = true
}

# ── Autostart ─────────────────────────────────────────
exec-once = waybar
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets

# ── Keybindings ───────────────────────────────────────
$mod = SUPER

# Core
bind = $mod, Return, exec, foot
bind = $mod, Q, killactive
bind = $mod SHIFT, Q, exit
bind = $mod, Space, togglefloating
bind = $mod, F, fullscreen
bind = $mod, P, pseudo
bind = $mod, J, togglesplit

# Apps
bind = $mod, D, exec, wofi --show drun
bind = $mod SHIFT, Return, exec, foot -e tmux
bind = $mod, B, exec, firefox
bind = $mod, E, exec, foot -e ranger
bind = $mod, C, exec, foot -e nvim

# Screenshots
bind = , Print, exec, grimblast copy area
bind = $mod, Print, exec, grimblast save area ~/Pictures/screenshots/$(date +%Y%m%d_%H%M%S).png
bind = $mod SHIFT, Print, exec, grimblast copy output

# Audio (ThinkPad T460 function keys)
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute,        exec, wpctl set-mute   @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute,     exec, wpctl set-mute   @DEFAULT_SOURCE@ toggle

# Brightness (ThinkPad T460 backlight)
bindel = , XF86MonBrightnessUp,   exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Workspace navigation
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Focus movement
bind = $mod, left,  movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up,    movefocus, u
bind = $mod, down,  movefocus, d

# Window resize
binde = $mod CTRL, right, resizeactive, 20 0
binde = $mod CTRL, left,  resizeactive, -20 0
binde = $mod CTRL, up,    resizeactive, 0 -20
binde = $mod CTRL, down,  resizeactive, 0 20

# Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Special workspace (scratchpad)
bind = $mod, S, togglespecialworkspace, magic
bind = $mod SHIFT, S, movetoworkspace, special:magic

# Scroll through workspaces
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up,   workspace, e-1

# Window rules
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = pin,title:^(Picture-in-Picture)$
windowrulev2 = opacity 0.85,class:^(foot)$
EOF

    # hyprpaper config
    cat > "${hypr_cfg_dir}/hyprpaper.conf" <<'EOF'
preload = ~/.config/hypr/wallpaper.jpg
wallpaper = eDP-1,~/.config/hypr/wallpaper.jpg
splash = false
EOF

    chown -R 1000:1000 "${LFS}/home/flint"
}

_configure_waybar() {
    local wb_dir="${LFS}/home/flint/.config/waybar"
    mkdir -p "${wb_dir}"

    cat > "${wb_dir}/config.jsonc" <<'EOF'
// ─── Flint Linux Waybar Config ───────────────────────────────────────────────
{
    "layer": "top",
    "position": "top",
    "height": 32,
    "spacing": 4,
    "margin-top": 4,
    "margin-left": 8,
    "margin-right": 8,

    "modules-left": [
        "hyprland/workspaces",
        "hyprland/submap",
        "hyprland/window"
    ],
    "modules-center": [
        "clock"
    ],
    "modules-right": [
        "cpu",
        "memory",
        "temperature",
        "backlight",
        "battery",
        "network",
        "pulseaudio",
        "tray"
    ],

    "hyprland/workspaces": {
        "format": "{icon}",
        "format-icons": {
            "1": "①", "2": "②", "3": "③", "4": "④", "5": "⑤",
            "6": "⑥", "7": "⑦", "8": "⑧", "9": "⑨", "10": "⑩",
            "active": "",
            "default": "○",
            "urgent": "●"
        },
        "on-scroll-up": "hyprctl dispatch workspace e+1",
        "on-scroll-down": "hyprctl dispatch workspace e-1",
        "all-outputs": false,
        "persistent-workspaces": {
            "*": [1,2,3,4,5]
        }
    },

    "hyprland/window": {
        "format": " {}",
        "max-length": 40,
        "separate-outputs": true
    },

    "clock": {
        "format": "  {:%A %b %d   %H:%M}",
        "format-alt": "  {:%Y-%m-%d %H:%M:%S}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "interval": 1,
        "calendar": {
            "mode": "month",
            "weeks-pos": "right",
            "on-scroll": 1
        }
    },

    "cpu": {
        "format": " {usage}%",
        "interval": 2,
        "on-click": "foot -e htop",
        "tooltip-format": "i7-6600U — {avg_frequency} GHz"
    },

    "memory": {
        "format": " {}%",
        "interval": 5,
        "on-click": "foot -e htop",
        "tooltip-format": "{used:0.1f}G / {total:0.1f}G"
    },

    "temperature": {
        "hwmon-path": "/sys/class/hwmon/hwmon1/temp1_input",
        "critical-threshold": 80,
        "format": " {temperatureC}°C",
        "format-critical": " {temperatureC}°C",
        "interval": 5
    },

    "backlight": {
        "device": "intel_backlight",
        "format": "{icon} {percent}%",
        "format-icons": ["", "", "", "", "", "", "", "", ""],
        "on-scroll-up": "brightnessctl set 5%+",
        "on-scroll-down": "brightnessctl set 5%-"
    },

    "battery": {
        "states": {
            "warning": 25,
            "critical": 10
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-icons": ["", "", "", "", ""],
        "interval": 30,
        "tooltip-format": "{timeTo} — {power:.1f}W"
    },

    "network": {
        "format-wifi": "  {signalStrength}%",
        "format-ethernet": "  {ipaddr}",
        "format-linked": " (No IP)",
        "format-disconnected": "⚠ Offline",
        "format-alt": "{ifname}: {ipaddr}/{cidr}",
        "tooltip-format-wifi": "{essid} ({signalStrength}%) — {frequency} MHz",
        "tooltip-format-ethernet": "{ifname} — {ipaddr}",
        "on-click-right": "foot -e nmtui",
        "interval": 10
    },

    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-muted": "  Muted",
        "format-icons": {
            "headphone": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol",
        "on-scroll-up": "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+",
        "on-scroll-down": "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    },

    "tray": {
        "icon-size": 18,
        "spacing": 6
    }
}
EOF

    # Waybar CSS (Nord color scheme)
    cat > "${wb_dir}/style.css" <<'EOF'
/* ─── Flint Linux Waybar Style — Nord Theme ─────────────────────────────── */

@define-color nord0  #2e3440;
@define-color nord1  #3b4252;
@define-color nord2  #434c5e;
@define-color nord3  #4c566a;
@define-color nord4  #d8dee9;
@define-color nord5  #e5e9f0;
@define-color nord6  #eceff4;
@define-color nord7  #8fbcbb;
@define-color nord8  #88c0d0;
@define-color nord9  #81a1c1;
@define-color nord10 #5e81ac;
@define-color nord11 #bf616a;
@define-color nord12 #d08770;
@define-color nord13 #ebcb8b;
@define-color nord14 #a3be8c;
@define-color nord15 #b48ead;

* {
    font-family: "JetBrainsMono Nerd Font", "Noto Sans", monospace;
    font-size: 13px;
    border: none;
    border-radius: 0;
}

window#waybar {
    background-color: alpha(@nord0, 0.90);
    color: @nord4;
    transition-property: background-color;
    transition-duration: 0.5s;
    border-radius: 10px;
}

#workspaces button {
    padding: 0 6px;
    background-color: transparent;
    color: @nord3;
    border-radius: 6px;
    margin: 3px 2px;
    transition: all 0.3s ease;
}
#workspaces button:hover {
    background: @nord2;
    color: @nord8;
}
#workspaces button.active {
    background-color: @nord10;
    color: @nord6;
    font-weight: bold;
}
#workspaces button.urgent {
    background-color: @nord11;
    color: @nord6;
}

#window {
    color: @nord4;
    padding: 0 8px;
}

#clock {
    color: @nord8;
    font-weight: bold;
    padding: 0 12px;
}

#cpu {
    color: @nord14;
    padding: 0 8px;
}
#memory {
    color: @nord15;
    padding: 0 8px;
}
#temperature {
    color: @nord12;
    padding: 0 8px;
}
#temperature.critical {
    color: @nord11;
    animation: blink 1s linear infinite;
}
#backlight {
    color: @nord13;
    padding: 0 8px;
}
#battery {
    color: @nord14;
    padding: 0 8px;
}
#battery.warning {
    color: @nord13;
}
#battery.critical {
    color: @nord11;
    animation: blink 1s linear infinite;
}
#battery.charging {
    color: @nord14;
}
#network {
    color: @nord7;
    padding: 0 8px;
}
#network.disconnected {
    color: @nord11;
}
#pulseaudio {
    color: @nord9;
    padding: 0 8px;
}
#pulseaudio.muted {
    color: @nord3;
}
#tray {
    padding: 0 6px;
}

@keyframes blink {
    to { color: @nord0; background-color: @nord11; }
}
EOF

    chown -R 1000:1000 "${LFS}/home/flint/.config/waybar"
}

_configure_foot() {
    local foot_dir="${LFS}/home/flint/.config/foot"
    mkdir -p "${foot_dir}"

    cat > "${foot_dir}/foot.ini" <<'EOF'
# ─── Flint Linux — Foot Terminal Configuration ───────────────────────────────

[main]
term=foot
font=JetBrainsMono Nerd Font:size=11
font-bold=JetBrainsMono Nerd Font:weight=Bold:size=11
dpi-aware=yes
pad=6x6
shell=/usr/bin/bash
login-shell=no
workers=4

[scrollback]
lines=10000
indicator-position=relative
indicator-format=percentage

[cursor]
style=beam
color=88c0d0 2e3440
blink=yes

[mouse]
hide-when-typing=yes

[colors]
# Nord color scheme
background=2e3440
foreground=d8dee9
regular0=3b4252
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=81a1c1
regular5=b48ead
regular6=88c0d0
regular7=e5e9f0
bright0=4c566a
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=81a1c1
bright5=b48ead
bright6=8fbcbb
bright7=eceff4
alpha=0.92

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+r
font-increase=Control+equal
font-decrease=Control+minus
font-reset=Control+0
spawn-terminal=Control+Shift+n
EOF

    chown -R 1000:1000 "${LFS}/home/flint/.config/foot"
}

_configure_fastfetch() {
    local ff_dir="${LFS}/home/flint/.config/fastfetch"
    mkdir -p "${ff_dir}"

    cat > "${ff_dir}/config.jsonc" <<'EOF'
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "type": "builtin",
        "source": "linux",
        "color": {
            "1": "blue",
            "2": "cyan"
        },
        "padding": {
            "left": 1,
            "top": 1
        }
    },
    "display": {
        "separator": "  →  ",
        "color": "cyan",
        "keyColor": "blue",
        "keyWidth": 14
    },
    "modules": [
        {
            "type": "title",
            "format": "{user}@{hostname}",
            "color": "blue"
        },
        "break",
        {
            "type": "os",
            "key": "OS",
            "format": "Flint Linux {version} (LFS)"
        },
        {
            "type": "kernel",
            "key": "Kernel"
        },
        {
            "type": "uptime",
            "key": "Uptime"
        },
        {
            "type": "packages",
            "key": "Packages"
        },
        {
            "type": "shell",
            "key": "Shell"
        },
        {
            "type": "wm",
            "key": "WM",
            "format": "Hyprland"
        },
        {
            "type": "terminal",
            "key": "Terminal"
        },
        "break",
        {
            "type": "cpu",
            "key": "CPU",
            "format": "{name} ({cores-physical}C/{cores-logical}T) @ {freq-max:.2}GHz"
        },
        {
            "type": "gpu",
            "key": "GPU",
            "format": "{name} (Intel HD 520, Skylake GT2)"
        },
        {
            "type": "memory",
            "key": "Memory",
            "format": "{used} / {total} ({percentage:.0}%)"
        },
        {
            "type": "swap",
            "key": "Swap/Zram",
            "format": "{used} / {total}"
        },
        {
            "type": "disk",
            "key": "Disk",
            "folders": "/"
        },
        "break",
        {
            "type": "colors",
            "paddingLeft": 1,
            "symbol": "circle"
        }
    ]
}
EOF

    # Bashrc additions for flint user
    cat >> "${LFS}/home/flint/.bashrc" <<'EOF'

# ─── Flint Linux Environment ─────────────────────────────────────────────────
export LANG=en_US.UTF-8
export EDITOR=vim
export VISUAL=vim

# Hyprland auto-start on TTY1
if [[ -z "${WAYLAND_DISPLAY}" ]] && [[ "$(tty)" == "/dev/tty1" ]]; then
    exec Hyprland 2>/tmp/hyprland.log
fi

# Fastfetch on login
command -v fastfetch &>/dev/null && fastfetch

# Aliases
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -lahF'
alias la='ls -A'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias pacman='pacman --color=auto'

# Pacman helpers
alias pacs='pacman -Ss'      # search
alias paci='pacman -S'       # install
alias pacr='pacman -Rs'      # remove
alias pacu='pacman -Syu'     # update
alias pacl='pacman -Q'       # list installed
alias paco='pacman -Qdt'     # orphans
EOF

    chown -R 1000:1000 "${LFS}/home/flint"
}

_configure_zram_service() {
    # dinit service for zram
    local dinit_dir="${LFS}/etc/dinit.d"
    mkdir -p "${dinit_dir}/scripts"

    cat > "${dinit_dir}/zram-swap" <<'EOF'
type = scripted
command = /etc/dinit.d/scripts/zram-setup.sh
before = boot
logfile = /var/log/dinit/zram.log
EOF

    cat > "${dinit_dir}/scripts/zram-setup.sh" <<'EOF'
#!/bin/bash
# Flint Linux — Zram swap setup (4GB compressed swap on 12GB RAM machine)
set -e

ZRAM_SIZE="4G"
ZRAM_ALGO="lz4"    # lz4 is fastest; use zstd for better compression
ZRAM_PRIORITY=100  # Higher than disk swap

modprobe zram num_devices=1

# Set compression algorithm
echo "${ZRAM_ALGO}" > /sys/block/zram0/comp_algorithm

# Set disk size
echo "${ZRAM_SIZE}" > /sys/block/zram0/disksize

# Optional: multi-stream compression (uses more CPU, better throughput)
echo "$(nproc)" > /sys/block/zram0/max_comp_streams 2>/dev/null || true

# Format and activate
mkswap --label zram0 /dev/zram0
swapon --priority "${ZRAM_PRIORITY}" /dev/zram0

echo "Zram swap activated: ${ZRAM_SIZE} (${ZRAM_ALGO})"
EOF
    chmod +x "${dinit_dir}/scripts/zram-setup.sh"
}

_finalize_system() {
    local FINAL_SCRIPT="${LFS}/sources/flint_finalize.sh"
    cat > "${FINAL_SCRIPT}" <<'FINAL'
#!/bin/bash
set -euo pipefail

# ldconfig
ldconfig

# Generate locales
locale-gen 2>/dev/null || true

# /etc/os-release (Flint Linux identity)
cat > /etc/os-release <<'EOF'
NAME="Flint Linux"
PRETTY_NAME="Flint Linux 1.0 (Obsidian)"
VERSION="1.0"
VERSION_CODENAME="Obsidian"
ID=flint
ID_LIKE=arch
BUILD_ID=rolling
HOME_URL="https://github.com/flintlinux"
DOCUMENTATION_URL="https://github.com/flintlinux/wiki"
ANSI_COLOR="1;34"
EOF

cat > /etc/flint-release <<'EOF'
Flint Linux 1.0 Obsidian
Built with LFS 12 + Skylake optimizations
Init: dinit | WM: Hyprland | Pkgmgr: Pacman
EOF

# /etc/issue
cat > /etc/issue <<'EOF'

  ███████╗██╗     ██╗███╗   ██╗████████╗
  ██╔════╝██║     ██║████╗  ██║╚══██╔══╝
  █████╗  ██║     ██║██╔██╗ ██║   ██║
  ██╔══╝  ██║     ██║██║╚██╗██║   ██║
  ██║     ███████╗██║██║ ╚████║   ██║
  ╚═╝     ╚══════╝╚═╝╚═╝  ╚═══╝   ╚═╝
  Flint Linux 1.0 Obsidian — \l

EOF

# /etc/motd
cat > /etc/motd <<'EOF'
Welcome to Flint Linux!
  Default credentials: flint / flint  (CHANGE IMMEDIATELY: passwd flint)
  Root password:       root  / flint  (CHANGE IMMEDIATELY: passwd root)
  Package manager: pacman -Syu
  Bootloader: run 'grub-install' and 'grub-mkconfig -o /boot/grub/grub.cfg'
EOF

# /etc/inputrc
cat > /etc/inputrc <<'EOF'
set bell-style none
set horizontal-scroll-mode off
set meta-flag on
set input-meta on
set convert-meta off
set output-meta on
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5~": history-search-backward
"\e[6~": history-search-forward
EOF

# Cleanup temp files
rm -rf /tmp/flint_build /tmp/build_pkg /tmp/*_build 2>/dev/null || true

echo "Finalization complete."
FINAL
    chmod +x "${FINAL_SCRIPT}"
    chroot "${LFS}" /usr/bin/env -i HOME=/root PATH=/usr/bin:/usr/sbin \
        bash /sources/flint_finalize.sh
}

# ─────────────────────────────────────────────────────────────────────────────
# UNMOUNT AND CLEANUP
# ─────────────────────────────────────────────────────────────────────────────
cleanup_mounts() {
    banner "Unmounting virtual filesystems"
    local mounts=(
        "${LFS}/dev/pts"
        "${LFS}/dev/shm"
        "${LFS}/dev"
        "${LFS}/proc"
        "${LFS}/run"
        "${LFS}/sys"
    )
    for m in "${mounts[@]}"; do
        if mountpoint -q "${m}" 2>/dev/null; then
            umount -v "${m}" || umount -vl "${m}"
        fi
    done
    success "Mounts cleaned up."
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN ENTRYPOINT
# ─────────────────────────────────────────────────────────────────────────────
main() {
    local phase="${1:-all}"

    clear
    echo -e "${BOLD}${BLUE}"
    cat <<'BANNER'
  ███████╗██╗     ██╗███╗   ██╗████████╗
  ██╔════╝██║     ██║████╗  ██║╚══██╔══╝
  █████╗  ██║     ██║██╔██╗ ██║   ██║
  ██╔══╝  ██║     ██║██║╚██╗██║   ██║
  ██║     ███████╗██║██║ ╚████║   ██║
  ╚═╝     ╚══════╝╚═╝╚═╝  ╚═══╝   ╚═╝
BANNER
    echo -e "${NC}"
    echo -e "  ${BOLD}Flint Linux ${FLINT_VERSION} (${FLINT_CODENAME})${NC} — Automated LFS Builder"
    echo -e "  Target: ThinkPad T460 | i7-6600U Skylake | 12GB RAM"
    echo -e "  Build root: ${LFS}"
    echo -e "  Parallelism: -j${JOBS}"
    echo ""

    case "${phase}" in
        check)
            preflight_check
            ;;
        1|phase1)
            preflight_check
            setup_environment
            phase1_toolchain
            ;;
        2|phase2)
            setup_chroot_mounts
            phase2_chroot_system
            ;;
        3|phase3)
            setup_chroot_mounts
            phase3_postinstall
            cleanup_mounts
            ;;
        all)
            preflight_check
            setup_environment
            phase1_toolchain
            setup_chroot_mounts
            phase2_chroot_system
            phase3_postinstall
            cleanup_mounts
            ;;
        *)
            echo "Usage: $0 [all|check|1|2|3]"
            echo ""
            echo "  all    — Run everything (default)"
            echo "  check  — Pre-flight check only"
            echo "  1      — Phase 1: Cross-toolchain"
            echo "  2      — Phase 2: Final system (chroot)"
            echo "  3      — Phase 3: Post-install"
            exit 1
            ;;
    esac

    if [[ "${phase}" == "all" || "${phase}" == "3" || "${phase}" == "phase3" ]]; then
        echo ""
        banner "🔥 Flint Linux Build Complete!"
        echo -e "${GREEN}${BOLD}"
        cat <<'DONE'
  ╔══════════════════════════════════════════════════════════════╗
  ║  BUILD SUCCESSFUL — Next steps:                              ║
  ║                                                              ║
  ║  1. chroot /mnt/lfs                                          ║
  ║  2. grub-install --target=x86_64-efi \                       ║
  ║       --efi-directory=/boot/efi       \                       ║
  ║       --bootloader-id=FLINT           \                       ║
  ║       --recheck                                              ║
  ║     (or for BIOS: grub-install /dev/sdX)                    ║
  ║  3. grub-mkconfig -o /boot/grub/grub.cfg                     ║
  ║  4. passwd root  (set root password)                         ║
  ║  5. passwd flint (set user password)                         ║
  ║  6. exit && reboot                                           ║
  ║                                                              ║
  ║  Post-boot: pacman-key --populate && pacman -Syu             ║
  ╚══════════════════════════════════════════════════════════════╝
DONE
        echo -e "${NC}"
    fi
}

# Trap for cleanup on exit
trap 'echo -e "\n${YELLOW}Build interrupted. Re-run to resume from last completed step.${NC}"' INT TERM

main "$@"
